/**
 * \file
 *
 * \brief Driver initialization.
 *
 (c) 2020 Microchip Technology Inc. and its subsidiaries.

    Subject to your compliance with these terms,you may use this software and
    any derivatives exclusively with Microchip products.It is your responsibility
    to comply with third party license terms applicable to your use of third party
    software (including open source software) that may accompany Microchip software.

    THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER
    EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED
    WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A
    PARTICULAR PURPOSE.

    IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE,
    INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND
    WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS
    BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE
    FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN
    ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
    THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *
 */

/*
 * Code generated by START.
 *
 * This file will be overwritten when reconfiguring your START project.
 * Please copy examples or other code you want to keep to a separate file
 * to avoid losing it when reconfiguring.
 */

#include "driver_init.h"
#include <system.h>

/* configure the pins and initialize the registers */
void USART_SCRN_initialization(void)
{

	// Set pin direction to input
	TX_SCRN_set_dir(PORT_DIR_IN);

	TX_SCRN_set_pull_mode(
	    // <y> Pull configuration
	    // <id> pad_pull_config
	    // <PORT_PULL_OFF"> Off
	    // <PORT_PULL_UP"> Pull-up
	    PORT_PULL_OFF);

	/* set the alternate pin mux */

	PORTMUX.USARTROUTEA |= PORTMUX_USART00_bm;

	// Set pin direction to output

	RX_SCRN_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	RX_SCRN_set_dir(PORT_DIR_OUT);

	/* set the alternate pin mux */

	PORTMUX.USARTROUTEA |= PORTMUX_USART00_bm;

	USART_SCRN_init();
}

/* configure the pins and initialize the registers */
void USART_WIFI_initialization(void)
{

	// Set pin direction to input
	TX_WIFI_set_dir(PORT_DIR_IN);

	TX_WIFI_set_pull_mode(
	    // <y> Pull configuration
	    // <id> pad_pull_config
	    // <PORT_PULL_OFF"> Off
	    // <PORT_PULL_UP"> Pull-up
	    PORT_PULL_OFF);

	// Set pin direction to output

	RX_WIFI_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	RX_WIFI_set_dir(PORT_DIR_OUT);

	USART_WIFI_init();
}

/* configure the pins and initialize the registers */
void USART_TEMP_initialization(void)
{

	// Set pin direction to input
	AUX2_set_dir(PORT_DIR_IN);

	AUX2_set_pull_mode(
	    // <y> Pull configuration
	    // <id> pad_pull_config
	    // <PORT_PULL_OFF"> Off
	    // <PORT_PULL_UP"> Pull-up
	    PORT_PULL_OFF);

	// Set pin direction to output

	AUX1_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	AUX1_set_dir(PORT_DIR_OUT);

	USART_TEMP_init();
}

/* configure the pins and initialize the registers */
void USART_3_initialization(void)
{

	// Set pin direction to input
	RX0_set_dir(PORT_DIR_IN);

	RX0_set_pull_mode(
	    // <y> Pull configuration
	    // <id> pad_pull_config
	    // <PORT_PULL_OFF"> Off
	    // <PORT_PULL_UP"> Pull-up
	    PORT_PULL_OFF);

	/* set the alternate pin mux */

	PORTMUX.USARTROUTEA |= PORTMUX_USART30_bm;

	// Set pin direction to output

	TX0_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	TX0_set_dir(PORT_DIR_OUT);

	/* set the alternate pin mux */

	PORTMUX.USARTROUTEA |= PORTMUX_USART30_bm;

	USART_3_init();
}

/**
 * \brief System initialization
 */
void system_init()
{
	mcu_init();

	/* PORT setting on PC4 */

	// Set pin direction to output

	second_stage_heat_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	second_stage_heat_set_dir(PORT_DIR_OUT);

	/* PORT setting on PC5 */

	// Set pin direction to output

	second_stage_cool_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	second_stage_cool_set_dir(PORT_DIR_OUT);

	/* PORT setting on PC6 */

	// Set pin direction to output

	first_stage_cool_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	first_stage_cool_set_dir(PORT_DIR_OUT);

	/* PORT setting on PC7 */

	// Set pin direction to output

	Hum_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	Hum_set_dir(PORT_DIR_OUT);

	/* PORT setting on PD0 */

	// Set pin direction to output

	Mode_A_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	Mode_A_set_dir(PORT_DIR_OUT);

	/* PORT setting on PD1 */

	// Set pin direction to output

	Mode_B_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	Mode_B_set_dir(PORT_DIR_OUT);

	/* PORT setting on PD2 */

	// Set pin direction to output

	OTA1_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	OTA1_set_dir(PORT_DIR_OUT);

	/* PORT setting on PD3 */

	// Set pin direction to output

	TEST_LED_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	TEST_LED_set_dir(PORT_DIR_OUT);

	/* PORT setting on PE3 */

	// Set pin direction to output

	Dehum_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	Dehum_set_dir(PORT_DIR_OUT);

	/* PORT setting on PF4 */

	// Set pin direction to output

	PWM_C02_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	PWM_C02_set_dir(PORT_DIR_OUT);

	/* PORT setting on PF5 */

	// Set pin direction to output

	RYD_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	RYD_set_dir(PORT_DIR_OUT);

	/* PORT setting on PF6 */

	// Set pin direction to input
	RESET_set_dir(PORT_DIR_IN);

	RESET_set_pull_mode(
	    // <y> Pull configuration
	    // <id> pad_pull_config
	    // <PORT_PULL_OFF"> Off
	    // <PORT_PULL_UP"> Pull-up
	    PORT_PULL_OFF);

	CLKCTRL_init();

	VREF_0_init();

	USART_SCRN_initialization();

	USART_WIFI_initialization();

	USART_TEMP_initialization();

	USART_3_initialization();

	WDT_0_init();

	CPUINT_init();

	SLPCTRL_init();

	BOD_init();
}
