all:
	(cd udp; make all)
	(cd tcp; make all)

install:
	(cd udp; make install INSTDIR=/usr/local/bin)
	(cd tcp; make install INSTDIR=/usr/local/bin)

clean:
	(cd udp; make clean)
	(cd tcp; make clean)