
#.PHONEY: all foo bar baz


#foo: bar
#	@echo In $@ temp $(temp)

#bar: temp = local scope
#bar:
#	@echo in $@ temp $(temp)
	
#temp = global scope


#all: foo bar
#	@echo In $@ temp $(temp)
	
all foo bar baz: ; @echo In $@ VAR is $(VAR)